---
version: "2.1"
services:
  organizr:
    container_name: organizr
    environment:
      - "PUID=${PUID}"
      - "PGID=${PGID}"
      - "TZ=${TZ}"
    image: organizr/organizr
    ports:
      - "${OGANIZRPORT}:80"
    restart: unless-stopped
    volumes:
      - "${APPDATA}/organizr:/config"
